### ISSUE TITLE
Better documentation for the object storage replication

### ISSUE THREAD

**Issue by JMLX42** [ovh/docs#1204]
Hello,

The following page:

https://www.ovhcloud.com/en/public-cloud/object-storage/

states that:

> Your data is distributed within clusters that have triple replication for each object. These replicas are placed on both different disks and servers, to ensure their longevity.
> 
> [...]
> 
> What SLA does OVHcloud offer for accessing the Object Storage service?
> 
> The SLA guarantees 99.9% monthly availability for accessing the Object Storage service. For further information, please refer to the Terms & conditions.
> What SLA does OVHcloud offer for data resilience on the Object Storage service?
> 
> The data resilience rate is 100% for the Object Storage service. For further information, please refer to the Terms & conditions.

But it doesn't explain *where* the replication happens.

- If I create a bucket in the GRA region, is the replication happening in GRA? What if GRA burns down entirely?
- How is the 100% resilience guaranteed in this case? Is there an off-site cold storage? How much time to restore it?

I think those questions needs to be addressed in order to better understand the benefits/risks involved with the OVH Object Storage service, plan accordingly and avoid data loss.

Regards,

**Comment by JMLX42** [comment]
X-posted on the OVH Community forums: https://community.ovh.com/t/object-storage-et-replication/41329

**Comment by BertrandBordage** [comment]
From the [Public Cloud terms and conditions](https://www.ovh.com/world/support/termsofservice/specific_conditions_public_cloud.pdf):

> 6.3 OVHcloud does not backup specific data on the Instances or Object Storage Containers of the Client. It is
therefore the responsibility of the Client to take all the necessary measures to back up their data in the event
of data loss or deterioration of entrusted data, whatever the cause, including causes not expressly mentioned
in this Contract. OVHcloud does not provide any guarantees related to the Client’s use of the Services, in
particular guarantees related to the security and preservation of this data.

That’s hard to accept, because I’m not sure there is a better way to backup data from Object Storage than fetching all objects every day, which costs a significant amount of money. In my case that would make the backup cost way more than the normal usage of the Object Storage itself.

This is literaly the only place where I don’t do backups myself every day because I got sold by marketing semi-truths.

If OVH confirms that all replications are at the same location, there’s no point in using Object Storage in my opinion :slightly_frowning_face:

**Comment by JMLX42** [comment]
@BertrandBordage thank you for taking the time to read and quote the ToS.

> 6.3 OVHcloud does not backup specific data on the Instances or Object Storage Containers of the Client. It is
> therefore the responsibility of the Client to take all the necessary measures to back up their data in the event
> of data loss or deterioration of entrusted data, whatever the cause [...] OVHcloud does  not  provide  any  guarantees  related  to  the Client’s use of the Services, in particular guarantees related to the security and preservation of this data. 

Also in the ToS:

> 7.16 In no circumstances is OVHcloud under any obligation, in respect of the cloud computing technologies it uses for the management of the Client’s Instances and the Object Storage Containers, to ensure the retention of Client data. All measures to ensure the backup of data is exclusively the responsibility of the Client. 
>
> [...]
>
> ARTICLE 12:SERVICE LEVEL AGREEMENT (SLA)
>
> [...]
>
> (g)Object Storage: Monthly availability rate: 99.90%
> Monthly availability rate of data stored in Object Storage Container: 99.999%.  
>
> [...]
> 
> “Durability” means that: the  capacity  of  OVHcloud  to  provide  the Client access  again  to  the  data  that  was stored in the Object Storage Container prior to an incident of unavailability which has been duly notified (see the following conditions). 
> 
> [...]
> 
> Failure to comply with the durability rate of data stored in Object Storage: Where the monthly durability rate in Article 12.1 is not achieved, reimbursement equal to 100% of the monthly fee paid by the Client for the affected Object Storage Container.

**Except** there is not a single "Durability rate" for any service in the "ARTICLE 12:SERVICE LEVEL AGREEMENT (SLA)" section or anywhere in the ToS. Let alone for Object Storage.

IMHO that's in total contradiction with the Object Storage FAQ that states:

> The data resilience rate is 100% for the Object Storage service. For further information, please refer to the Terms & conditions.

So the ToS is missing the 100% Durability for "(g) Object Storage" or the documentation is wrong about the data resilience.

**Even if the "ARTICLE 12:SERVICE LEVEL AGREEMENT (SLA)" is amended to add a 100% Durability to the Object Storage, it conflicts with sections 6.3 and 7.16**, that deny such guarantee. So simply adding a 100% Durability rate to Article 12 (g) Object Storage is not enough.

**Comment by BertrandBordage** [comment]
Yes, this looks like standard legal disclaimers that didn’t take so much into account the specificities of Object Storage…

**Comment by JMLX42** [comment]
As of today, still no answer from OVH neither here, nor on [the community forums](https://community.ovh.com/t/object-storage-et-replication/41329) nor in the support ticket created in my admin panel.

**Comment by BertrandBordage-zoetis** [comment]
And the OVHCloud app has been showing a server error for at least a week on the Object Storage page…
![image](https://user-images.githubusercontent.com/80327264/114151721-b386f680-991d-11eb-94f4-b66ee6eca3e8.png)

**Comment by BertrandBordage** [comment]
And the OVHCloud app has been showing a server error for at least a week on the Object Storage page…
![image](https://user-images.githubusercontent.com/1119169/114152285-65262780-991e-11eb-83b4-108388766266.png)

**Comment by JMLX42** [comment]
I had to open a separate ticket because I'm not able to delete 2 test buckets.

**Comment by HNGamingUK** [comment]
> And the OVHCloud app has been showing a server error for at least a week on the Object Storage page…
> ![image](https://user-images.githubusercontent.com/1119169/114152285-65262780-991e-11eb-83b4-108388766266.png)

Obviously a rather late reply. 

I have yet to raise a ticket because of that bug but it seems to do that on initial load of object storage or cloud archive. If you click try again and then object storage or cloud archive it works okay then.

**Comment by BertrandBordage** [comment]
@HNGamingUK I clicked try again and click again on Object Storage, but I'm still facing the error :\

**Comment by HNGamingUK** [comment]
> @HNGamingUK I clicked try again and click again on Object Storage, but I'm still facing the error :\

Interesting, seems to work for me so far. I am unsure if it might be a good idea to raise an issue on the following repo: https://github.com/ovh/manager 

Going back to the original point I too have been unable to find confirmation on how data is specifically "triple replicated" ie same DC/Multiple DCs/Cross region. 

I am about to start storing data into Cloud Archive which touts itself as "Secure and reliable" but does not mention how is is so. If I store archive/backup data I expect it to be redundant! I am UK based so wanting to use the UK region but also seemingly it only has one DC so if it is not replicated across regions then if the UK DC burns down say like another region did... then I would loose ALL my backup data... 

This is also relevant to the Object Storage also, since it could be production data and if using the UK region and no replication across regions then again if UK DC dies then ALL production data is lost. 

I am aware that OVH is much cheaper than say AWS (bit bad to try and compare considering Amazon's size) but at least with AWS you have full documentation on how the replication works and I quote the AWS site: "Amazon S3 Standard, S3 Standard-IA, and S3 Glacier storage classes redundantly store your objects on multiple devices across a minimum of three Availability Zones (AZs) in an Amazon S3 Region before returning SUCCESS." 

I think this is a long enough rant message now, I have raised multiple support tickets so far requesting information around Object Storage and Cloud Archive shall continue to chase and see if they reply...

**Comment by HNGamingUK** [comment]
@JMLX42 had a reply from OVH support:

"I'm afraid Replication happens within the same region within the same DC, in different server."

**Comment by JMLX42** [comment]
> I'm afraid Replication happens within the same region

That's bad.

> within the same DC, in different server."

Oh that's **very** bad.

**Comment by HNGamingUK** [comment]
> > I'm afraid Replication happens within the same region
> 
> That's bad.
> 
> > within the same DC, in different server."
> 
> Oh that's **very** bad.

Very much agree with you there, I am awaiting a reply around if they plan to improve the redundancy. 

I have also questioned if it is the same for Cloud Archive

**Comment by HNGamingUK** [comment]
@JMLX42  This is likely to be my last update but OVH have replied: 

"We are always trying to improve our products and services, for the time being there is no ETA on when will that be available but i would recommend having the replicas setup by yourself as to have different replications in different locations." 

Looking at the pricing compared to say S3 (which replicate between all 3 availability zones inside a region) it is ~3x cheaper. As the saying goes "Cheaper doesn't always mean better"

If you are fine with it being replicated inside a single DC then continue on but if you need the high level of redundancy then S3 would be better.

**Comment by JMLX42** [comment]
The SLA and the Terms and Conditions have been updated a few months ago but I forgot to update this issue. This matter is now resolved. So I'm closing this issue.
