### ISSUE TITLE
What are the "OVHcloud groups" for dns nameservers (eg. dns19.ovh.net vs dns12.ovh.net) and how are they assinged?

### ISSUE THREAD

**Issue by errnesto** [ovh/docs#3469]
When I create dns zone records they are assinged a nameserver with a number prefix.
So far for me it is always 12 (dns12.ovh.net and ns12.ovh.net)

The only place I found this mentioned is the warning in this section: https://github.com/ovh/docs/blob/develop/pages/web/domains/dns_server_general_information/guide.en-gb.md#modifying-dns-servers

My usecase is that we hand these nameservers out to custumers so we can setup their domain config for them.
It would be nice to always have the same address (or ip), that we can use for all our dns zones, so we can include it in our documentation.

So I have two questions:

- how are these servers assinged when I create a new dns zone (will I always get the same for all my dns zones that I create in the future)?
- can I somehow change the assinged servers?

**Comment by Kazarus4** [comment]
Hello @ernesto

DNS servers are allocated randomly, depending on the remaining available space on the server.
You cannot choose which DNS server your DNS zone will be saved to.

I suggest you replace the numbers with some `X` in your documentation (e.g. [dnsXX.ovh.net](https://dnsxx.ovh.net/) instead of [dns12.ovh.net](https://dns12.ovh.net/)) and asking your customers to replace the X with the right number corresponding to their server.

Best regards
